# config/config.yaml

env:
  render: false
  input_shape: [1, 100, 160]
  actions: 3

training:
  episodes: 500
  max_steps: 1000
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.1
  epsilon_decay: 0.995
  learning_rate: 0.0001
  batch_size: 64
  memory_size: 10000
  target_update_freq: 10
  checkpoint_freq: 50
