env:
  render: false
  input_shape: [2,100, 160]  #  Pon [3, H, W] aquí, el canal 4 se agrega dinámicamente
  actions: 3
  scenario_path: config/defend_the_center.cfg
  
training:
  episodes: 1000
  max_steps: 500
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.005
  epsilon_decay: 0.9977
  learning_rate: 0.0005
  batch_size: 64
  memory_size: 4000
  target_update_freq: 10
  checkpoint_freq: 50
  checkpoint_path: checkpoints/defend_the_center_dqn_profundidas
model:
  type: dqn_att  # Opciones: dqn, dqn_att, dqn_att_yolo
